config/routes.rb
Rails.application.routes.draw do
  resources :collected_emails, only: [:create, :destroy]
  resources :settings, only: :update
  resources :slices, only: [:create, :update, :destroy]

  post 'clientside', to: 'settings#clientside'

  post 'mailchimp_api_key_verification', to: 'settings#mailchimp_api_key_verification'
  post 'klaviyo_api_key_verification', to: 'settings#klaviyo_api_key_verification'

  post 'add_url_filter/:id', to: 'settings#add_url_filter'
  delete 'remove_url_filter/:id', to: 'settings#remove_url_filter'

  post 'create_discount_code', to: 'home#create_discount_code'
  delete 'destroy_discount_code/:id', to: 'home#destroy_discount_code'

  get 'activatecharge', to: 'home#activatecharge'

  get 'collected_emails_pagination', to: 'home#collected_emails_pagination'

  post 'customers_redact', to: 'gdpr_webhooks#customers_redact'
  post 'shop_redact', to: 'gdpr_webhooks#shop_redact'

  root to: 'home#index'
  mount ShopifyApp::Engine, at: '/'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  require 'sidekiq/web'
  require 'admin_constraint'
  Sidekiq::Web.set :session_secret, Rails.application.secrets[:secret_key_base]
  mount Sidekiq::Web => '/sidekiq'
end

app/models/collected_email.rb
class CollectedEmail < ApplicationRecord
  belongs_to :shop
end

app/controllers/collected_emails_controller.rb
class CollectedEmailsController < ApplicationController
  before_action :set_collected_email, only: [:show, :edit, :update, :destroy]
  require 'net/http'

  def create
    @shop = Shop.find_by(shopify_domain: params[:shop_domain])
    @email = params[:collected_email]
    @settings = Setting.find_by( shop_id: @shop.id )
    if CollectedEmail.exists?(email: @email)
      render json: { status: 'ok', settings: @settings }
    else
      @collected_email = CollectedEmail.create(email: @email, shop_id: @shop.id)
      if @settings.mailchimp_enable
        gibbon = Gibbon::Request.new(api_key: @settings.mailchimp_api_key)
        gibbon.lists(@settings.mailchimp_list_id).members.create(body: {email_address: @email, status: "subscribed" })
      end
      if @settings.klaviyo_enable
        url = URI("https://a.klaviyo.com/api/v1/list/#{@settings.klaviyo_list_id}/members")
        req = Net::HTTP::Post.new(url)
        req.set_form_data({'api_key'=>"#{@settings.klaviyo_api_key}", 'email'=>"#{@email}", 'confirm_optin'=>false})
        http = Net::HTTP.new(url.host, url.port)
        http.use_ssl = (url.scheme == "https")
        response = http.request(req)
        puts response.body
      end
      render json: { status: 'ok', settings: @settings}
    end
  end

  def destroy
    @collected_email.destroy
    render json: { status: 'ok'}
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_collected_email
      @collected_email = CollectedEmail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def collected_email_params
      params.require(:collected_email).permit(:email, :shop_id)
    end
end

app/helpers/collected_emails_helper.rb
module CollectedEmailsHelper
end

app/views/collected_emails/_form.html.erb
<%= form_with(model: collected_email, local: true) do |form| %>
  <% if collected_email.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(collected_email.errors.count, "error") %> prohibited this collected_email from being saved:</h2>

      <ul>
      <% collected_email.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :collected_email_email %>
  </div>

  <div class="field">
    <%= form.label :shop_id %>
    <%= form.text_field :shop_id, id: :collected_email_shop_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/collected_emails/edit.html.erb
<h1>Editing Collected Email</h1>

<%= render 'form', collected_email: @collected_email %>

<%= link_to 'Show', @collected_email %> |
<%= link_to 'Back', collected_emails_path %>

app/views/collected_emails/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Collected Emails</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Shop</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @collected_emails.each do |collected_email| %>
      <tr>
        <td><%= collected_email.email %></td>
        <td><%= collected_email.shop %></td>
        <td><%= link_to 'Show', collected_email %></td>
        <td><%= link_to 'Edit', edit_collected_email_path(collected_email) %></td>
        <td><%= link_to 'Destroy', collected_email, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Collected Email', new_collected_email_path %>

app/views/collected_emails/new.html.erb
<h1>New Collected Email</h1>

<%= render 'form', collected_email: @collected_email %>

<%= link_to 'Back', collected_emails_path %>

app/views/collected_emails/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @collected_email.email %>
</p>

<p>
  <strong>Shop:</strong>
  <%= @collected_email.shop %>
</p>

<%= link_to 'Edit', edit_collected_email_path(@collected_email) %> |
<%= link_to 'Back', collected_emails_path %>