config/routes.rb
Rails.application.routes.draw do
  resources :collected_emails, only: [:create, :destroy]
  resources :settings, only: :update
  resources :slices, only: [:create, :update, :destroy]

  post 'clientside', to: 'settings#clientside'

  post 'mailchimp_api_key_verification', to: 'settings#mailchimp_api_key_verification'
  post 'klaviyo_api_key_verification', to: 'settings#klaviyo_api_key_verification'

  post 'add_url_filter/:id', to: 'settings#add_url_filter'
  delete 'remove_url_filter/:id', to: 'settings#remove_url_filter'

  post 'create_discount_code', to: 'home#create_discount_code'
  delete 'destroy_discount_code/:id', to: 'home#destroy_discount_code'

  get 'activatecharge', to: 'home#activatecharge'

  get 'collected_emails_pagination', to: 'home#collected_emails_pagination'

  post 'customers_redact', to: 'gdpr_webhooks#customers_redact'
  post 'shop_redact', to: 'gdpr_webhooks#shop_redact'

  root to: 'home#index'
  mount ShopifyApp::Engine, at: '/'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  require 'sidekiq/web'
  require 'admin_constraint'
  Sidekiq::Web.set :session_secret, Rails.application.secrets[:secret_key_base]
  mount Sidekiq::Web => '/sidekiq'
end

app/models/setting.rb
class Setting < ApplicationRecord
  belongs_to :shop
  has_many :slices, dependent: :destroy
  mount_uploader :big_logo, BigImageUploader
  mount_uploader :small_logo, SmallImageUploader
  mount_uploader :tab_icon, TabIconUploader
  mount_uploader :facebook_image, FacebookDesktopUploader
  mount_uploader :facebook_image_mobile, FacebookMobileUploader
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  before_action :set_setting, only: [:update, :add_url_filter, :remove_url_filter]
  require 'net/http'

  def create
    @setting = Setting.new(setting_params)

    respond_to do |format|
      if @setting.save
        format.html { redirect_to @setting, notice: 'Settings were successfully created.' }
        format.json { render :show, status: :created, location: @setting }
      else
        format.html { render :new }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /settings/1
  # PATCH/PUT /settings/1.json
  def update
    respond_to do |format|
      if @setting.update(setting_params)
        format.html { redirect_to root_path, notice: 'Settings were successfully updated.' }
        format.json { render :show, status: :ok, location: @setting }
      else
        format.html { render :edit }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  def add_url_filter
    url = params[:url_filters]
    @setting.url_filters.push(url)
    if @setting.save
      render json: { url: url}
    else
      render json: {status: :unprocessable_entity}
    end
  end

  def remove_url_filter
    @setting.url_filters.delete(params[:url_filters])
    if @setting.save
      render json: { status: 'ok' }
    else
      render json: {status: :unprocessable_entity}
    end
  end

  def clientside
    @shop = Shop.find_by(shopify_domain: params[:shop_domain])
    @settings = Setting.find_or_create_by(shop_id: @shop.id)
    @slices = Slice.where(setting_id: @settings.id).order("id ASC")
    render json: { shop: @shop, settings: @settings, slices: @slices }
  end

  def mailchimp_api_key_verification
    gibbon = Gibbon::Request.new(api_key: params[:api_key])
    begin
      @mailchimp_lists = gibbon.lists.retrieve
      render json: { mailchimp_lists: @mailchimp_lists }
    rescue Gibbon::MailChimpError => e
      puts "MailChimpError: #{e.message} - #{e.raw_body}"
    end
  end

  def klaviyo_api_key_verification
    uri = URI('https://a.klaviyo.com/api/v1/lists')
    parameters = { api_key: params[:api_key], type: 'list' }
    uri.query = URI.encode_www_form(parameters )
    res = Net::HTTP.get_response(uri)
    if res.is_a?(Net::HTTPSuccess)
      render json: { klaviyo_lists: res.body }
    else
      render json: { errors: res.body }, status: 409
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_setting
      @setting = Setting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def setting_params
      params.require(:setting).permit(:enable, :big_logo, :small_logo, :title_text,
      :disclaimer_text, :guiding_text, :enter_email, :invalid_email_message, :spin_button,
      :close_button, :winning_title, :winning_text, :discount_code_title, :continue_button,
      :copied_message, :reject_discount_button, :free_product_description, :free_product_button,
      :free_product_reject, :discount_coupon_code_bar, :close_button_in_bar, :theme, :background_color,
      :font_color, :bold_text_and_button_color, :win_section_color, :lose_section_color,
      :enable_discount_code_bar, :discount_code_bar_countdown_time, :discount_code_bar_position,
      :enable_progress_bar, :progress_bar_text, :progress_bar_color, :progress_bar_percentage, :progress_bar_position,
      :show_on_desktop, :show_on_mobile, :show_on_desktop_leave_intent, :show_on_mobile_leave_intent,
      :show_on_desktop_after, :show_on_mobile_after, :show_on_desktop_seconds, :show_on_mobile_seconds,
      :show_pull_out_tab, :tab_icon, :do_not_show_app, :discount_coupon_auto_apply, :url_filters,
      :mailchimp_enable, :mailchimp_list_id, :mailchimp_api_key, :klaviyo_enable, :klaviyo_api_key, :klaviyo_list_id, :duo_color,
      :facebook_enable, :facebook_title, :facebook_link, :facebook_desc, :facebook_button, :facebook_text_color, :facebook_button_text_color,
      :facebook_button_color, :facebook_image, :facebook_image_mobile, :default_tab_icon)
    end
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/settings/_form.html.haml
= form_with(model: setting, local: true) do |form|
  - if setting.errors.any?
    #error_explanation
      %h2
        = pluralize(setting.errors.count, "error")
        prohibited this setting from being saved:
      %ul
        - setting.errors.full_messages.each do |message|
          %li= message

      %h3 Slices
      = form.fields_for :slices do |slice|
        = render 'slice_fields', form: slice
      .links
        = link_to_add_association 'add slice', form, :slices

  .actions
    = form.submit

app/views/settings/_slice_fields.html.haml
.nested-fields
  .field
    = form.label :lose
    %br
    = form.check_box :lose
  .field
    = form.label :type
    %br
    = form.text_field :type
  .field
    = form.label :label
    %br
    = form.text_field :label
  .field
    = form.label :code
    %br
    = form.text_field :code
  .field
    = form.label :gravity
    %br
    = form.select(:gravity) do
      - [[0, 0], [10, 10], [20, 20], [30, 30], [40, 40], [50, 50], [60, 60], [70, 70], [80, 80], [90, 90], [100, 100] ].each do |c|
        = content_tag(:option, c.first, value: c.last)
  .field

  = link_to_remove_association "remove slice", form

app/views/settings/edit.html.erb
<h1>Editing Setting</h1>

<%= render 'form', setting: @setting %>

<%= link_to 'Show', @setting %> |
<%= link_to 'Back', settings_path %>

app/views/settings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Settings</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @settings.each do |setting| %>
      <tr>
        <td><%= link_to 'Show', setting %></td>
        <td><%= link_to 'Edit', edit_setting_path(setting) %></td>
        <td><%= link_to 'Destroy', setting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Setting', new_setting_path %>

app/views/settings/new.html.erb
<h1>New Setting</h1>

<%= render 'form', setting: @setting %>

<%= link_to 'Back', settings_path %>

app/views/settings/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_setting_path(@setting) %> |
<%= link_to 'Back', settings_path %>